import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";

import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/AppSidebar";
import AppNavigation from '../components/AppNavigation';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const inter = Geist({
  variable: "--font-inter",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`max-h-[100vh] ${geistSans.variable} ${inter.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider open={true} >
          <AppSidebar />
          <main className={"overflow-scroll max-h-[100vh] w-full "}>
            <AppNavigation />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
